[package]
name = "skippable_map"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.108"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
